### ISSUE TITLE
comparing unicode and byte strings can cause UnicodeDecodeError

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SEBDYA/googletransitdatafeed#144]
```
In Python 2.5 it causes a warning:

transitfeed.py:921: UnicodeWarning: Unicode equal comparison failed to
convert both arguments to Unicode - interpreting them as being unequal
  (self.route_desc == self.route_long_name))):

but recently I ran this is python2.4 and it caused a test failure.
Explanation: http://www.python.org/doc/2.5/whatsnew/other-lang.html

I'm not sure if it is worth fixing this specific case instead of doing
something bigger, like keeping all values as utf-8 encoded bytes.

======================================================================
ERROR: runTest (testtransitfeed.BadProblemReporterTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/testtransitfeed.py", line 512, in runTest
    loader.Load()
  File "transitfeed.py", line 3825, in Load
    self._LoadRoutes()
  File "transitfeed.py", line 3583, in _LoadRoutes
    self._schedule.AddRouteObject(route, self._problems)
  File "transitfeed.py", line 2668, in AddRouteObject
    route.Validate(problem_reporter)
  File "transitfeed.py", line 919, in Validate
    if (self.route_desc and
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 2:
ordinal not in range(128)

======================================================================
ERROR: runTest (testtransitfeed.NoExceptionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/testtransitfeed.py", line 152, in runTest
    schedule = loader.Load()
  File "transitfeed.py", line 3825, in Load
    self._LoadRoutes()
  File "transitfeed.py", line 3583, in _LoadRoutes
    self._schedule.AddRouteObject(route, self._problems)
  File "transitfeed.py", line 2668, in AddRouteObject
    route.Validate(problem_reporter)
  File "transitfeed.py", line 919, in Validate
    if (self.route_desc and
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 2:
ordinal not in range(128)

----------------------------------------------------------------------
Ran 292 tests in 39.465s

```

Original issue reported on code.google.com by `tom.brow...@gmail.com` on 27 Feb 2009 at 10:17

**Comment by GoogleCodeExporter** [comment]
```
fixed by http://codereview.appspot.com/25045 rev 1011, to be included in next 
release
```

Original comment by `tom.brow...@gmail.com` on 20 Mar 2009 at 11:56
- Changed state: **Fixed**
