### ISSUE TITLE
Unused service/trip id crashes (feed)merge application

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SEBDYA/googletransitdatafeed#146]
```
What steps will reproduce the problem?
1. Create feed dataset with unused trip id/service id combination(s) (i.e. 
using a service id - like "HOL"iday that is not scheduled to any of the 
dates in the specific range of the calendar.txt file)
2. Attempt to merge with another feed dataset
3.

What is the expected output? What do you see instead?
Expect to see merged output dataset, receive instead following errors in 
command window:
Traceback (most recent call last):
  File "merge.py", line 1716, in <module>
  File "merge.py", line 1686, in main
  File "transitfeed.pyc", line 3765, in Load
  File "transitfeed.pyc", line 3641, in _LoadTrips
  File "transitfeed.pyc", line 2714, in AddTripObject
  File "transitfeed.pyc", line 164, in InvalidValue
  File "transitfeed.pyc", line 384, in _Report
transitfeed.InvalidValue: Invalid value HOL in field service_id

What version of the product are you using? On what operating system?
transitfeed-windows-binary-1.1.9.zip
Windows XP

Please provide any additional information below.
See issue 145 for more complete description.  Need to have unscheduled 
trips in the feed file (both original and to some extent merged), for 
compatibility with the Timetable Publisher application - which reads the 
data for output to print formats for the public (i.e. html or pdf 
schedules).  If the merged feed file happened to be compatible with TTPUB, 
this might allow for comparisons across two otherwise distinct schedule 
databases (based on effective date)

```

Original issue reported on code.google.com by `tsob...@cityofmadison.com` on 2 Mar 2009 at 2:40

**Comment by GoogleCodeExporter** [comment]
Original comment by `tom.brow...@gmail.com` on 21 Aug 2009 at 8:54
- Changed state: **Duplicate**
- Added labels: **App-Merge**, **Language-Python**, **Type-Defect**
