### ISSUE TITLE
In Windows setup.py install crashes with "No such file or directory"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SEBDYA/googletransitdatafeed#199]
```
What steps will reproduce the problem?
1.svn up
2.python setup.py install


What is the expected output? What do you see instead?
install succeed, but:
Writing D:\Python26\Lib\site-packages\transitfeed-1.2.3-py2.6.egg-info
Traceback (most recent call last):
  File "setup.py", line 111, in <module>
    z = zipfile.ZipFile(zipfile_path, 'a')
  File "D:\Python26\lib\zipfile.py", line 684, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory:
'transitfeed-windows-binary-1.2.3\
\library.zip'

What version of the product are you using? On what operating system?
svn head, windows

Please provide any additional information below.

```

Original issue reported on code.google.com by `redaready.dev` on 6 Nov 2009 at 11:16

**Comment by GoogleCodeExporter** [comment]
```
I think the install succeeded but the hack at the end of setup.py crashed. Fix 
is to 
change the condition from
if has_py2exe:
to something that is only true when building py2exe executables.

This should only happen on machines with py2exe installed.
```

Original comment by `tom.brow...@gmail.com` on 7 Nov 2009 at 12:45
- Changed title: **In Windows setup.py install crashes with "No such file or directory"**
- Added labels: **Difficulty-Moderate**, **Language-Python**, **OpSys-Windows**, **Priority-Low**, **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
Moved to https://github.com/google/transitfeed/issues/199
```

Original comment by `bdfer...@google.com` on 8 Oct 2014 at 12:09
- Changed state: **WontFix**
