### ISSUE TITLE
Unit tests fail in Python 2.6 due to changes to zipfile

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SEBDYA/googletransitdatafeed#237]
```
What steps will reproduce the problem?
1. Run the unit tests in Python 2.6 after a clean checkout

What is the expected output? What do you see instead?
I expect the tests to pass. Instead they fail with errors like

======================================================================
ERROR: testDuplicateTransfer (testtransitfeed.TransferValidationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anog/trunk/python/test/testtransitfeed.py", line 2880, in 
testDuplicateTransfer
    "stop_times.txt", self.zip.read("stop_times.txt") +
  File "/usr/lib/python2.6/zipfile.py", line 834, in read
    return self.open(name, "r", pwd).read()
  File "/usr/lib/python2.6/zipfile.py", line 874, in open
    zinfo.orig_filename, fname)
BadZipfile: File name in directory "stop_times.txt" and header "stops.txt" 
differ.

Running the unit tests in Python 2.6 but with the Python 2.5 zipfile.py 
library shows no such errors, so there must be a breaking change in the 
library. I quickly checked the documentation but found nothing interesting, 
I must read it more carefully and try to figure out what's going on.

This error has occurred for a long time now, but I could find no mention of 
it in the groups. Since Ubuntu 10.04 now comes with Python 2.6 and 2.5 
can't be installed from the (default) repositories it might be a good idea 
to fix this before the next release.
```

Original issue reported on code.google.com by `a...@google.com` on 24 May 2010 at 5:01

**Comment by GoogleCodeExporter** [comment]
```
This looked interesting so I looked into it a bit. Either there is a zipfile 
bug or a problem with 
how we use it. I suspect closing the zip between each operation would fix it. 
This reproduces the 
problem


from StringIO import StringIO
import zipfile

s = StringIO()
zf = zipfile.ZipFile(s, 'a')
zf.writestr("d.txt", "DDDDDDDDDD")
zf.writestr("a.txt", "AAAAAAAAAA")
zf.read("d.txt")
zf.writestr("c.txt", "CCCCCCCCCC")
zf.read("a.txt")

This zipfile source is really easy to read and in svn... 
http://svn.python.org/view/python/branches/release26-maint/Lib/zipfile.py?sortby
=date&view=log

Ahh, I suspect this is you :-)
http://stackoverflow.com/questions/2920793/python-2-6-does-not-like-appending-to
-existing-archives-
in-zip-files
```

Original comment by `tom.brow...@gmail.com` on 27 May 2010 at 4:41

**Comment by GoogleCodeExporter** [comment]
```
Yep, that's me - I had good luck with stackoverflow in the past, so I thought 
I'd give it a try :)

I tried to quickly look at the source and add some debugging info there, but I 
couldn't figure out what was going on. 
Basically it grabs the correct archive inside the zip, but fails because it 
things it has the wrong one.

I had tried closing the file, it doesn't work. Not even creating a new StringIO 
with the contents of the old one (after 
closing the zipfile) and creating a new ZipFile with that. Reading "a.txt" from 
the new ZipFile will still fail with the 
exact same message.

The documentation does explicitly say that you can read in append mode, so I 
think this should work... And we're read()'ing 
by passing it a filename, so the caveat described in open() does not apply. 
Changing your example to use a "real" disk-
based zip file makes it work. Doing the same in the transitfeed unit tests, 
however, changes no failures.

Oh well, the best thing to do is probably to stop wasting time on this and 
really separate the reads from the writes in the 
tests. Though I'd really like to know the actual cause of this, investigating 
it (much) further is probably not worth the 
time :(
```

Original comment by `a...@google.com` on 27 May 2010 at 7:53

**Comment by GoogleCodeExporter** [comment]
```
I'd file a http://bugs.python.org/ and if it is ignored I'll nag Guido next 
time I see 
him ;-)
```

Original comment by `tom.brow...@gmail.com` on 28 May 2010 at 8:10

**Comment by GoogleCodeExporter** [comment]
```
Moved to https://github.com/google/transitfeed/issues/237
```

Original comment by `bdfer...@google.com` on 8 Oct 2014 at 12:17
- Changed state: **WontFix**
