### ISSUE TITLE
FeedValidator fails badly when blank values are provided for stops.txt/stop_lat & stop_lon

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SEBDYA/googletransitdatafeed#258]
```
What steps will reproduce the problem?
1. Create a feed with the following last four lines of stops.txt:

stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,locatio
n_type,parent_station
...
place_0CNsu#,,"CANET SUD (SL)",,           ,           ,,,1,
place_0PEc#,,"CATALOGNE (SL)",,           ,           ,,,1,
place_0PEsn#,,"SNCF (SL)",,           ,           ,,,1,
place_0PEv1#,,"VAUBAN (SL)",,           ,           ,,,1,

2. Run FeedValidator over this file

What is the expected output? What do you see instead?


I expect a sensible error message. I see it generates the following error:

------
validating ./google_transit.zip
Yikes, the program threw an unexpected exception!

Hopefully a complete report has been saved to transitfeedcrash.txt,
though if you are seeing this message we've already disappointed you once
today. Please include the report in a new issue at
http://code.google.com/p/googletransitdatafeed/issues/entry
or an email to the public group googletransitdatafeed@googlegroups.com. Sorry!

------------------------------------------------------------
transitfeed version 1.2.6

File 
"/usr/lib/python2.5/site-packages/transitfeed-1.2.6-py2.5.egg/EGG-INFO/scripts/f
eedvalidator.py", line 688, in main
       else:
 -->     return RunValidationOutputFromOptions(feed, options)

    feed = ./google_transit.zip
    usage = %prog [options] [<input GTFS.zip>]

Validates GTFS file (or directory) <input GTFS.zip> and writes a HTML
report of the results to validation-results.html.

If <input GTFS.zip> is ommited the filename is read from the console. Dragging
a file into the console may enter the filename.

For more information see
http://code.google.com/p/googletransitdatafeed/wiki/FeedValidator

    args = ['./google_transit.zip']
    parser = <transitfeed.util.OptionParserLongError instance at 0xb74e60>
    options = {'check_duplicate_trips': False, 'manual_entry': False, 'extension': None, 'memory_db': True, 'service_gap_interval': 13, 
'latest_version': '', 'limit_per_type': 20, 'performance': None, 'output': 
'./validation-results.html'}

File 
"/usr/lib/python2.5/site-packages/transitfeed-1.2.6-py2.5.egg/EGG-INFO/scripts/f
eedvalidator.py", line 477, in RunValidationOutputF
romOptions
       else:
 -->     return RunValidationOutputToFilename(feed, options, options.output)

    feed = ./google_transit.zip
    options = {'check_duplicate_trips': False, 'manual_entry': False, 'extension': None, 'memory_db': True, 'service_gap_interval': 13, 
'latest_version': '', 'limit_per_type': 20, 'performance': None, 'output': 
'./validation-results.html'}

File 
"/usr/lib/python2.5/site-packages/transitfeed-1.2.6-py2.5.egg/EGG-INFO/scripts/f
eedvalidator.py", line 484, in RunValidationOutputT
oFilename
         output_file = open(output_filename, 'w')
 -->     exit_code = RunValidationOutputToFile(feed, options, output_file)
         output_file.close()
    feed = ./google_transit.zip
    output_file = <open file './validation-results.html', mode 'w' at 0xc505d0>
    options = {'check_duplicate_trips': False, 'manual_entry': False, 'extension': None, 'memory_db': True, 'service_gap_interval': 13, 
'latest_version': '', 'limit_per_type': 20, 'performance': None, 'output': 
'./validation-results.html'}
    output_filename = ./validation-results.html

File 
"/usr/lib/python2.5/site-packages/transitfeed-1.2.6-py2.5.egg/EGG-INFO/scripts/f
eedvalidator.py", line 502, in RunValidationOutputT
oFile
       schedule, exit_code, other_problems_string = RunValidation(feed, options,
 -->                                                              problems)
       if isinstance(feed, basestring):
    feed = ./google_transit.zip
    accumulator = <__main__.HTMLCountingProblemAccumulator object at 0xc197d0>
    output_file = <open file './validation-results.html', mode 'w' at 0xc505d0>
    problems = <transitfeed.problems.ProblemReporter object at 0xc19910>
    options = {'check_duplicate_trips': False, 'manual_entry': False, 'extension': None, 'memory_db': True, 'service_gap_interval': 13, 
'latest_version': '', 'limit_per_type': 20, 'performance': None, 'output': 
'./validation-results.html'}

File 
"/usr/lib/python2.5/site-packages/transitfeed-1.2.6-py2.5.egg/EGG-INFO/scripts/f
eedvalidator.py", line 558, in RunValidation
                                    gtfs_factory=gtfs_factory)
 -->   schedule = loader.Load()
       schedule.Validate(service_gap_interval=options.service_gap_interval)
    feed = ./google_transit.zip
    problems = <transitfeed.problems.ProblemReporter object at 0xc19910>
    loader = <transitfeed.loader.Loader instance at 0xc510e0>
    extension_module = <module 'transitfeed' from '/usr/lib/python2.5/site-packages/transitfeed-1.2.6-py2.5.egg/transitfeed/__init__.pyc
'>
    options = {'check_duplicate_trips': False, 'manual_entry': False, 'extension': None, 'memory_db': True, 'service_gap_interval': 13, 
'latest_version': '', 'limit_per_type': 20, 'performance': None, 'output': 
'./validation-results.html'}
    other_problems_string = None
    gtfs_factory = <transitfeed.gtfsfactory.GtfsFactory object at 0xc4f250>

File 
"/usr/lib/python2.5/site-packages/transitfeed-1.2.6-py2.5.egg/transitfeed/loader
.py", line 554, in Load
         self._LoadShapes()
 -->     self._LoadFeed()

    self = <transitfeed.loader.Loader instance at 0xc510e0>

File 
"/usr/lib/python2.5/site-packages/transitfeed-1.2.6-py2.5.egg/transitfeed/loader
.py", line 400, in _LoadFeed
               instance.SetGtfsFactory(self._gtfs_factory)
 -->           if not instance.ValidateBeforeAdd(self._problems):
                 continue
    row_num = 86
    d = {'stop_lat': u'', 'stop_code': u'', 'stop_lon': u'', 'parent_station': u'', 'stop_url': u'', 'stop_id': u'place_0CNsu#', 'stop_d
esc': u'', 'stop_name': u'CANET SUD (SL)', 'location_type': u'1', 'zone_id': 
u''}
    header = ['stop_id', 'stop_code', 'stop_name', 'stop_desc', 'stop_lat', 'stop_lon', 'zone_id', 'stop_url', 'location_type', 'parent_
station']
    self = <transitfeed.loader.Loader instance at 0xc510e0>
    filename = stops.txt
    instance = <Stop [('location_type', 1), ('parent_station', u''), ('stop_code', u''), ('stop_desc', u''), ('stop_id', u'place_0CNsu#'
), ('stop_lat', u''), ('stop_lon', u''), ('stop_name', u'CANET SUD (SL)'), 
('stop_url', u''), ('zone_id', u'')]>
    loading_order = ['agency.txt', 'stops.txt', 'routes.txt', 'transfers.txt', 'trips.txt', 'fare_attributes.txt', 'fare_rules.txt', 'fr
equencies.txt']
    object_class = <class 'transitfeed.stop.Stop'>
    row = [u'place_0CNsu#', u'', u'CANET SUD (SL)', u'', u'', u'', u'', u'', u'1', u'']

File 
"/usr/lib/python2.5/site-packages/transitfeed-1.2.6-py2.5.egg/transitfeed/stop.p
y", line 236, in ValidateBeforeAdd
         # Check that this object is consistent with itself
 -->     self.ValidateStopNotTooCloseToOrigin(problems)
         self.ValidateStopDescriptionAndNameAreDifferent(problems)
    self = <Stop [('location_type', 1), ('parent_station', u''), ('stop_code', u''), ('stop_desc', u''), ('stop_id', u'place_0CNsu#'), (
'stop_lat', u''), ('stop_lon', u''), ('stop_name', u'CANET SUD (SL)'), 
('stop_url', u''), ('zone_id', u'')]>
    problems = <transitfeed.problems.ProblemReporter object at 0xc19910>

File 
"/usr/lib/python2.5/site-packages/transitfeed-1.2.6-py2.5.egg/transitfeed/stop.p
y", line 203, in ValidateStopNotTooCloseToOrigin
         if (self.stop_lat is not None and self.stop_lon is not None and
 -->         abs(self.stop_lat) < 1.0) and (abs(self.stop_lon) < 1.0):
           problems.InvalidValue('stop_lat', self.stop_lat,
    self = <Stop [('location_type', 1), ('parent_station', u''), ('stop_code', u''), ('stop_desc', u''), ('stop_id', u'place_0CNsu#'), (
'stop_lat', u''), ('stop_lon', u''), ('stop_name', u'CANET SUD (SL)'), 
('stop_url', u''), ('zone_id', u'')]>
    problems = <transitfeed.problems.ProblemReporter object at 0xc19910>

TypeError: bad operand type for abs(): 'unicode'


------------------------------------------------------------

Yikes, the program threw an unexpected exception!

Hopefully a complete report has been saved to transitfeedcrash.txt,
though if you are seeing this message we've already disappointed you once
today. Please include the report in a new issue at
http://code.google.com/p/googletransitdatafeed/issues/entry
or an email to the public group googletransitdatafeed@googlegroups.com. Sorry!


Press enter to continue...Traceback (most recent call last):
  File "/usr/bin/feedvalidator.py", line 5, in <module>
    pkg_resources.run_script('transitfeed==1.2.6', 'feedvalidator.py')
  File "/usr/lib/python2.5/site-packages/pkg_resources.py", line 448, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.5/site-packages/pkg_resources.py", line 1166, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.5/site-packages/transitfeed-1.2.6-py2.5.egg/EGG-INFO/scripts/feedvalidator.py", line 749, in <module>
    util.RunWithCrashHandler(main)
  File "/usr/lib/python2.5/site-packages/transitfeed-1.2.6-py2.5.egg/transitfeed/util.py", line 104, in RunWithCrashHandler
    raw_input('Press enter to continue...')
KeyboardInterrupt



What version of the product are you using? On what operating system?

1.2.6 on Linux



Please provide any additional information below.

Originally reported by a partner (ask richardrussell for more information 
including sample feed)
```

Original issue reported on code.google.com by `richardr...@google.com` on 4 Oct 2010 at 2:07

**Comment by GoogleCodeExporter** [comment]
```
Issue 262 has been merged into this issue.
```

Original comment by `tom.brow...@gmail.com` on 9 Nov 2010 at 1:44

**Comment by GoogleCodeExporter** [comment]
```
Feedvalidator also crashes when provided with empty strings in quotes: e.g. '' 
or ""
See Issue 269 and Issue 271
```

Original comment by `n...@google.com` on 3 Jan 2011 at 1:11

**Comment by GoogleCodeExporter** [comment]
```
Issue 269 has been merged into this issue.
```

Original comment by `n...@google.com` on 3 Jan 2011 at 1:17

**Comment by GoogleCodeExporter** [comment]
```
Issue 271 has been merged into this issue.
```

Original comment by `n...@google.com` on 3 Jan 2011 at 1:17

**Comment by GoogleCodeExporter** [comment]
Original comment by `n...@google.com` on 3 Jan 2011 at 1:18
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Revision 1419 changes the handling of empty (and also blank) strings in stop.py
See http://code.google.com/p/googletransitdatafeed/source/detail?r=1419
```

Original comment by `n...@google.com` on 14 Jan 2011 at 1:30
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `bdfer...@google.com` on 26 Sep 2014 at 4:44
- Added labels: **Language-Python**

**Comment by GoogleCodeExporter** [comment]
```
Issue 262 has been merged into this issue.
```

Original comment by `bdfer...@google.com` on 26 Sep 2014 at 4:45
