### ISSUE TITLE
Exception to use schedule_viewer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SEBDYA/googletransitdatafeed#292]
```
What steps will reproduce the problem?
1.First I generated the google_maps_api_key form http://localhost:8765/

2.To get schedule view, I have called the schedule_viewer.exe for Windows like 
bellow - 
Enter Feed Location: --key=ABQIAAAAyjhBA3yLy8Pb5I0j-hzTxhS5mHnTPZhpdPNxhTXqDyxEW
gZdyxTADkma4_ypcWUkUAXrD7VX-MNk3g C:\gtfs_navarra.zip

3.But the schedule viewer showing the error -
In feed '--key=ABQIAAAAyjhBA3yLy8Pb5I0j-hzTxhS5mHnTPZhpdPNxhTXqDyxEWgZdyxTADkma4
_ypcWUkUAXrD7VX-MNk3g C:\google_transit.zip':
Couldn't find a feed named
--key=ABQIAAAAyjhBA3yLy8Pb5I0j-hzTxhS5mHnTPZhpdPNxhTXqDyxEWgZdyxTADkma4_ypcWUkUA
XrD7VX-MNk3g
C:\gtfs_navarra.zip

To view, point your browser at http://localhost:8765/
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 59288)
Traceback (most recent call last):
  File "SocketServer.pyc", line 283, in _handle_request_noblock
  File "SocketServer.pyc", line 309, in process_request
  File "SocketServer.pyc", line 322, in finish_request
  File "SocketServer.pyc", line 617, in __init__
  File "BaseHTTPServer.pyc", line 329, in handle
  File "BaseHTTPServer.pyc", line 323, in handle_one_request
  File "schedule_viewer.py", line 107, in do_GET
  File "schedule_viewer.py", line 164, in handle_GET_home
  File "transitfeed\schedule.pyc", line 133, in GetStopBoundingBox
ValueError: min() arg is an empty sequence
----------------------------------------

4. Idon´t have idea what is happening ?

someone can help me?, please.



```

Original issue reported on code.google.com by `gabriela...@geoactio.com` on 27 Jun 2011 at 8:49

**Comment by GoogleCodeExporter** [comment]
```
Thank you for using the GTFS tools. You don't need a key to access the schedule 
viewer at http://localhost
You can even start it by double clicking on schedule_viewer.exe.
I updated the instructions at 
http://code.google.com/p/googletransitdatafeed/wiki/ScheduleViewer#Running_Windo
ws_exe
```

Original comment by `tom.brow...@gmail.com` on 27 Jun 2011 at 4:03
- Changed state: **Invalid**
- Added labels: **App-ScheduleViewer**, **Language-Python**
