### ISSUE TITLE
TransXChange2GTFS_1.7.5 conversion fails

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SEBDYA/googletransitdatafeed#356]
```
What steps will reproduce the problem?
1. Attempt to convert data from the 2011 NPTDR 
(http://data.gov.uk/dataset/nptdr): I followed to installation instructions for 
the conversion tool, tested it succesfully with the sample data (both under 
Linux and Win), and tried to convert an xml file for one specific area and 
transport mode.
2. No output is written. The messages are pasted below. The behaviour is the 
same under both OS.

What is the expected output? What do you see instead?

C:\Users\Hugo\TransXChange2GTFS_1.7.5>java -Xmx1080M -jar dist\transxchange2Goog
leTransit.jar c:\users\hugo\ATCO_209_BUS.xml anyagency Europe/London 3 exampleso
utput
transxchange2GTFS 1.7.5
Please refer to LICENSE file for licensing information
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 5, Size:
1
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at transxchange2GoogleTransitHandler.TransxchangeCalendar.calendarDuplic
ateService(TransxchangeCalendar.java:565)
        at transxchange2GoogleTransitHandler.TransxchangeTrips$1TripStructure.cr
eateTripStructure(TransxchangeTrips.java:228)
        at transxchange2GoogleTransitHandler.TransxchangeTrips.endElement(Transx
changeTrips.java:280)
        at transxchange2GoogleTransitHandler.TransxchangeHandlerEngine.endElemen
t(TransxchangeHandlerEngine.java:343)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endEleme
nt(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImp
l.scanEndElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImp
l$FragmentContentDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(U
nknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImp
l.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(U
nknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(U
nknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown So
urce)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Un
known Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.p
arse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown S
ource)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at transxchange2GoogleTransitHandler.TransxchangeHandler.parse(Transxcha
ngeHandler.java:164)
        at Transxchange2GoogleTransit.main(Transxchange2GoogleTransit.java:107)


What version of the product are you using? On what operating system?
version 1.7.5, tested under Linux (Xubuntu 12.04) and Windows (8).

Please provide any additional information below.

```

Original issue reported on code.google.com by `hugo.poe...@gmail.com` on 25 Jan 2013 at 3:26
- Merged into: #291

**Comment by GoogleCodeExporter** [comment]
```
You want https://github.com/drt24/googletransitdatafeed which fixes this 
problem among others.
```

Original comment by `scottish...@googlemail.com` on 25 Jan 2013 at 5:15

**Comment by GoogleCodeExporter** [comment]
```
Hi Hugo,
There are a number of issues that I've opened in June 2012 regarding the 
conversion of data in the NPTDR dataset format. The crash dump you've reported 
relates to the existing issue 291. 
Given this dataset is not been any updated (that I could tell), I did not 
pursue bugfixes any further. 
At any rate, Scottishphoenix fork is probably a good resource.

```

Original comment by `Joachim....@gmail.com` on 26 Jan 2013 at 8:07
- Changed state: **Duplicate**
