### ISSUE TITLE
Invalid route_color string causes stack dump

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SEBDYA/googletransitdatafeed#40]
```
We need to add validation to ColorLuminance or things that call it.

```

Original issue reported on code.google.com by `tom.brow...@gmail.com` on 28 Dec 2007 at 9:27

**Comment by GoogleCodeExporter** [comment]
```
Correction, IsValidColor should do this. But someone still found a way to get a 
stack
dump ending with "Invalid literal for int" in ColorLuminance(color). I'll get 
them to
send me the file.
```

Original comment by `tom.brow...@gmail.com` on 28 Dec 2007 at 9:32

**Comment by GoogleCodeExporter** [comment]
```
I checked the feed again with v 1.1.4. No stack dump.
```

Original comment by `tom.brow...@gmail.com` on 11 Jun 2008 at 12:13
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
```
An invalid route_color string also causes merge.exe to fail, instead of issuing 
an 
error.

Using merge.exe v 1.1.9

Traceback (most recent call last):
  File "merge.py", line 1716, in <module>
  File "merge.py", line 1687, in main
  File "transitfeed.pyc", line 3762, in Load

  File "transitfeed.pyc", line 3523, in _LoadRoutes

  File "transitfeed.pyc", line 2657, in AddRouteObject

  File "transitfeed.pyc", line 911, in Validate
    ☺c♦
  File "transitfeed.pyc", line 164, in InvalidValue
    name: a string, ignored when field_dict is present
  File "transitfeed.pyc", line 384, in _Report

transitfeed.InvalidValue: Invalid value 6600 in field route_color
route_color should be a valid color description which consists of 6 hexadecimal
characters representing the RGB values. Example: 44AA06
```

Original comment by `db.sd...@gmail.com` on 8 Jan 2009 at 4:38
